export const USER_SERVICE = 'USER_SERVICE';
export const TOKEN_SERVICE = 'JWT_SERVICE';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const LOGGER_SERVICE = 'WINSTON_SERVICE';

export const REQUEST_MIDDLEWARE = 'REQUEST_MIDDLEWARE';
export const EXCEPTION_HANDLER = 'EXCEPTION_HANDLER';